import { Buffer } from "buffer";
import { Client as ContractClient, Spec as ContractSpec, } from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";
if (typeof window !== "undefined") {
    //@ts-ignore Buffer exists
    window.Buffer = window.Buffer || Buffer;
}
export const networks = {
    testnet: {
        networkPassphrase: "Test SDF Network ; September 2015",
        contractId: "CCC7XVVJTLC7FIEYYDGVDNRR7SLACNJCSBV3EQRGOFPP6Y5L4DAYS22A",
    }
};
export class Client extends ContractClient {
    options;
    static async deploy(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options) {
        return ContractClient.deploy(null, options);
    }
    constructor(options) {
        super(new ContractSpec(["AAAAAQAAAAAAAAAAAAAABkVzY3JvdwAAAAAACQAAAAAAAAAGYW1vdW50AAAAAAALAAAAAAAAAAdhcmJpdGVyAAAAABMAAAAAAAAACGRlYWRsaW5lAAAABgAAAAAAAAAKbWlsZXN0b25lcwAAAAAD6gAAB9AAAAAJTWlsZXN0b25lAAAAAAAAAAAAAAVwYXllcgAAAAAAABMAAAAAAAAAEHJlbWFpbmluZ19hbW91bnQAAAALAAAAAAAAAAZzdGF0dXMAAAAAB9AAAAAMRXNjcm93U3RhdHVzAAAAAAAAAAV0b2tlbgAAAAAAABMAAAAAAAAABndvcmtlcgAAAAAAEw==",
            "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAAAgAAAAAAAAAAAAAADE5leHRFc2Nyb3dJZAAAAAEAAAAAAAAABkVzY3JvdwAAAAAAAQAAAAQ=",
            "AAAAAQAAAAAAAAAAAAAACU1pbGVzdG9uZQAAAAAAAAMAAAAAAAAABmFtb3VudAAAAAAACwAAAAAAAAACaWQAAAAAAAQAAAAAAAAABnN0YXR1cwAAAAAH0AAAAA9NaWxlc3RvbmVTdGF0dXMA",
            "AAAAAgAAAAAAAAAAAAAADEVzY3Jvd1N0YXR1cwAAAAQAAAAAAAAAAAAAAAZBY3RpdmUAAAAAAAAAAAAAAAAACFJlbGVhc2VkAAAAAAAAAAAAAAAIUmVmdW5kZWQAAAAAAAAAAAAAAAhEaXNwdXRlZA==",
            "AAAAAgAAAAAAAAAAAAAADURpc3B1dGVXaW5uZXIAAAAAAAACAAAAAAAAAAAAAAAGV29ya2VyAAAAAAAAAAAAAAAAAAVQYXllcgAAAA==",
            "AAAABQAAAAAAAAAAAAAADURpc3B1dGVPcGVuZWQAAAAAAAABAAAADmRpc3B1dGVfb3BlbmVkAAAAAAABAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAEAAAAAQAAAAI=",
            "AAAABQAAAAAAAAAAAAAADUVzY3Jvd0NyZWF0ZWQAAAAAAAABAAAADmVzY3Jvd19jcmVhdGVkAAAAAAABAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAEAAAAAQAAAAI=",
            "AAAABQAAAAAAAAAAAAAADkVzY3Jvd1JlZnVuZGVkAAAAAAABAAAAD2VzY3Jvd19yZWZ1bmRlZAAAAAABAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAEAAAAAQAAAAI=",
            "AAAAAgAAAAAAAAAAAAAAD01pbGVzdG9uZVN0YXR1cwAAAAACAAAAAAAAAAAAAAAHUGVuZGluZwAAAAAAAAAAAAAAAAhSZWxlYXNlZA==",
            "AAAABQAAAAAAAAAAAAAAD0Rpc3B1dGVSZXNvbHZlZAAAAAABAAAAEGRpc3B1dGVfcmVzb2x2ZWQAAAABAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAEAAAAAQAAAAI=",
            "AAAABQAAAAAAAAAAAAAAD0VzY3Jvd0NhbmNlbGxlZAAAAAABAAAAEGVzY3Jvd19jYW5jZWxsZWQAAAABAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAEAAAAAQAAAAI=",
            "AAAABQAAAAAAAAAAAAAAEU1pbGVzdG9uZVJlbGVhc2VkAAAAAAAAAQAAABJtaWxlc3RvbmVfcmVsZWFzZWQAAAAAAAIAAAAAAAAACWVzY3Jvd19pZAAAAAAAAAQAAAABAAAAAAAAAAxtaWxlc3RvbmVfaWQAAAAEAAAAAQAAAAI=",
            "AAAAAAAAAAAAAAAKZ2V0X2VzY3JvdwAAAAAAAQAAAAAAAAAJZXNjcm93X2lkAAAAAAAABAAAAAEAAAfQAAAABkVzY3JvdwAA",
            "AAAAAAAAAAAAAAAMb3Blbl9kaXNwdXRlAAAAAQAAAAAAAAAJZXNjcm93X2lkAAAAAAAABAAAAAA=",
            "AAAAAAAAAAAAAAANY2FuY2VsX2VzY3JvdwAAAAAAAAEAAAAAAAAACWVzY3Jvd19pZAAAAAAAAAQAAAAA",
            "AAAAAAAAAAAAAAANY3JlYXRlX2VzY3JvdwAAAAAAAAcAAAAAAAAABXBheWVyAAAAAAAAEwAAAAAAAAAGd29ya2VyAAAAAAATAAAAAAAAAAdhcmJpdGVyAAAAABMAAAAAAAAABXRva2VuAAAAAAAAEwAAAAAAAAAGYW1vdW50AAAAAAALAAAAAAAAAAhkZWFkbGluZQAAAAYAAAAAAAAACm1pbGVzdG9uZXMAAAAAA+oAAAfQAAAACU1pbGVzdG9uZQAAAAAAAAEAAAAE",
            "AAAAAAAAAAAAAAANcmVmdW5kX2VzY3JvdwAAAAAAAAEAAAAAAAAACWVzY3Jvd19pZAAAAAAAAAQAAAAA",
            "AAAAAAAAAAAAAAAPcmVzb2x2ZV9kaXNwdXRlAAAAAAIAAAAAAAAACWVzY3Jvd19pZAAAAAAAAAQAAAAAAAAABndpbm5lcgAAAAAH0AAAAA1EaXNwdXRlV2lubmVyAAAAAAAAAA==",
            "AAAAAAAAAAAAAAAQZ2V0X2VzY3Jvd19jb3VudAAAAAAAAAABAAAABA==",
            "AAAAAAAAAAAAAAARcmVsZWFzZV9taWxlc3RvbmUAAAAAAAACAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAEAAAAAAAAAAxtaWxlc3RvbmVfaWQAAAAEAAAAAA=="]), options);
        this.options = options;
    }
    fromJSON = {
        get_escrow: (this.txFromJSON),
        open_dispute: (this.txFromJSON),
        cancel_escrow: (this.txFromJSON),
        create_escrow: (this.txFromJSON),
        refund_escrow: (this.txFromJSON),
        resolve_dispute: (this.txFromJSON),
        get_escrow_count: (this.txFromJSON),
        release_milestone: (this.txFromJSON)
    };
}
